title: Документация Insomnia
email: support@insomnia.rest
description: >- # this means to ignore newlines until "baseurl:"
  Документация Insomnia: Предоставление высококачественных API-интерфейсов с помощью стандартов и сотрудничества с платформой разработки Insomnia API.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://insomnia.w3ref.ru" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: getinsomnia
github_username:  insomnia

# Build settings
theme: minima
plugins:
  - jekyll-feed

permalink: pretty

sass:
  sass_dir: assets/css

highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
